### ISSUE TITLE
Label wird nur angezeigt, wenn 'env_color' eingetragen wird

### ISSUE THREAD

**Issue by berecont** [bwein-net/contao-backend-customizer#8]
Problemstellung: Label wurde nicht angezeigt
Fehlerbehebung: ich musste `env_color` deklarieren

Gemäss der Beschreibung, müsste die Farbe nur dann deklariert werden, wenn `env_title` keine der vorgegebenen Phasen beschreibt.

Bug? Oder habe ich die Beschreibung missverstanden?

Contao 4.13.15
php81
Lokale Installation via Laragon

```
# config/parameters.yml
bwein_backend_customizer:
    env_title: 'local'
    env_color: '#FE3149'
    main_color: ''
```

**Comment by rabauss** [comment]
If no `env_color` is set and the title matches my fallback settings the color will be automatically set - see:
https://github.com/bwein-net/contao-backend-customizer/blob/41b9e3eb0be9e83f000c9f7c56096045c288d8c3/src/ParameterBag/BackendParameterBag.php#L86-L106

A working config should be:
```yaml
# config/parameters.yml
bwein_backend_customizer:
    env_title: 'local'
```

It is not possible anymore to set it empty like in the Readme, because of https://github.com/bwein-net/contao-backend-customizer/pull/5

I updated the Readme because since #5 the default values are `null`.
A working config would be also:
```yaml
# config/parameters.yml
bwein_backend_customizer:
    env_title: 'local'
    env_color: ~
    main_color: ~
```
